const Projects = [
  {
    title: 'Chudesa. Travel',
    type: ['style'],
    previewImage: 'Images/preview/chudesa_0.gif',
    projectImage: ['Images/project/chudesa.jpg'],
    link: 'chudesa',
    description: 'Логотип для небольшого агентства авторских туров по России',
    date: '2022',
    client: 'Chudesa. Travel',
    clientLink: 'https://www.instagram.com/chudesa.travel',
    tags: 'логотип, фирменный стиль'
  },
  {
    title: 'РА Навигатор',
    type: ['web'],
    previewImage: 'Images/preview/navig.jpg',
    projectImage: ['Images/project/navig.jpg'],
    link: 'navigator-web',
    description: 'Дизайн сайта для рекламного агентства Навигатор, представляющего собой комбо интернет-магазина и страниц-презентаций для каждого проекта',
    date: '2021',
    client: 'РА Навигатор',
    clientLink: 'https://ra-navigator.ru/',
    tags: 'веб-дизайн'
  },
  {
    title: 'Energy Point',
    type: ['style'],
    previewImage: 'Images/preview/energy_0.jpg',
    projectImage: ['Images/project/energy.jpg'],
    link: 'energy',
    description: 'Логотип и пример оформления для точек спортивного питания Energy Point от сети фитнес-клубов Gym Station (Киров)',
    date: '2021',
    client: 'Gym Station',
    clientLink: 'https://gym-s.ru',
    tags: 'логотип, фирменный стиль'
  },  
  
  {
    title: 'ВДНХ',
    type: ['graphics', 'style'],
    previewImage: 'Images/preview/vdnh.jpg',
    projectImage: ['Images/project/vdnh1.jpg', 'Images/project/vdnh2.jpg', 'Images/project/vdnh3.jpg', 'Images/project/plates.png'],
    link: 'vdnh',
    description: '3 воплощенных в жизнь концепции сувенирной продукции, которая продается на территории ВДНХ',
    date: '2021',
    client: 'РА Навигатор',
    clientLink: 'https://ra-navigator.ru/',
    tags: 'дизайн'
  },
  {
    title: 'ГТЛК',
    type: ['polygraphy'],
    previewImage: 'Images/preview/gtlk_00.jpg',
    projectImage: ['Images/project/gtlk.jpg'],
    link: 'gtlk',
    description: 'Дизайн и верстка годового отчета для самой крупной лизинговой компании России. Совместный проект со «Студией Космос»',
    date: '2021',
    client: 'ГТЛК',
    clientLink: 'https://gtlk.ru',
    tags: 'годовой отчет'
  },
  {
    title: 'La Mesto',
    type: ['web'],
    previewImage: 'Images/preview/lamesto.png',
    projectImage: ['Images/project/lamesto.jpg'],
    link: 'lamesto',
    description: 'Аренда элитной загородной недвижимости в Сочи и Красной Поляне',
    date: '2020',
    client: 'La Mesto',
    clientLink: 'https://lamesto.ru',
    tags: 'логотип, веб-дизайн'
  },
  {
    title: 'Центр Хруничева',
    type: ['polygraphy'],
    previewImage: 'Images/preview/rocket.jpg',
    projectImage: ['Images/project/rocket.jpg'],
    link: 'rocket',
    description: 'Имиджевый буклет для АО «Государственный космический научно-производственный центр имени М.В.Хруничева»',
    date: '2019',
    client: 'Центр Хруничева',
    clientLink: 'http://www.khrunichev.ru/',
    tags: 'буклет'
  },
  
  {
    title: 'Знаменский',
    type: ['polygraphy'],
    previewImage: 'Images/preview/znam_0.jpg',
    projectImage: ['Images/project/znam.jpg'],
    link: 'znamenskiy',
    description: 'Имиджевый буклет для продукции ветчинного дома Знаменский',
    date: '2019',
    client: 'Знаменский ветчинный дом',
    clientLink: 'http://www.nsgc.ru/novosti/275-znamenskij-sgts-i-znamenskij-vetchinnyj-dom-novyj-brend-na-gotovuyu-myasnuyu-produktsiyu-iz-svininy',
    tags: 'буклет'
  },
  {
    title: 'РА Навигатор',
    type: ['presentation', 'style'],
    previewImage: 'Images/preview/nav_prez_0.jpg',
    projectImage: ['Images/project/nav_prez.jpg'],
    link: 'nav-pres',
    description: 'Презентация для РА Навигатор',
    date: '2021',
    client: 'РА Навигатор',
    clientLink: 'https://ra-navigator.ru',
    tags: 'презентация'
  },
  {
    title: 'Home Credit Bank',
    type: ['polygraphy'],
    previewImage: 'Images/preview/calend.jpg',
    projectImage: ['Images/project/calend.jpg'],
    link: 'hcb',
    description: 'Концепция календаря для Home Credit Bank с клиентами банка, осуществившими свои мечты с помощью кредита',
    date: '2019',
    client: 'Home Credit Bank',
    clientLink: 'https://www.homecredit.ru/',
    tags: 'календарь'
  },
  {
    title: 'LØP',
    type: ['style', 'graphics'],
    previewImage: 'Images/preview/lop.jpg',
    projectImage: ['Images/project/lop.jpg'],
    link: 'lop',
    description: 'Логотип и упаковка для бренда здорового питания',
    date: '2019',
    client: 'LØP',
    clientLink: null,
    tags: 'графика, логотип, упаковка'
  },
  {
    title: 'Aeffect',
    type: ['style'],
    previewImage: 'Images/preview/aeffect.jpg',
    projectImage: ['Images/project/aeffect.jpg'],
    link: 'aeffect',
    description: 'Логотип и фирменный стиль ресторана в Санкт-Петербурге Концепция ресторана: каждую неделю новая мировая кухня Помимо египетского знака в логотипе есть греческий символ Ӕ',
    date: '2020',
    client: 'ресторан Aeffect',
    clientLink: 'https://aeffect.rest/',
    tags: 'логотип, фирменный стиль'
  },
  {
    title: 'Навыки мудрых',
    type: ['polygraphy'],
    previewImage: 'Images/preview/wisedom.png',
    projectImage: ['Images/project/wisdom.jpg'],
    link: 'wisedom',
    description: 'Отчет «Навыки мудрых» за пилотный год реализации специальной программы обучения предпенсионеров. Программа была разработана как мероприятие, связанное с увеличением пенсионного возраста. Программа обучения — это часть Национального проекта «Демография» и федерального проекта «Старшее поколение».',
    date: '2020',
    client: 'студия Космос',
    clientLink: 'https://kosmos.studio/',
    tags: 'буклет, годовой отчет'
  },
  {
    title: 'Gym Station',
    type: ['style'],
    previewImage: 'Images/preview/gym.jpg',
    projectImage: ['Images/project/gym1.jpg', 'Images/project/gym2.jpg'],
    link: 'gym',
    description: 'Для данного клиента разработана полная визуальная концепция – от логотипа до элементов интерьера, брендбук, сувенирная продукция, а также комплект маркетинговых материалов: наружная реклама, полиграфия, веб, презентация, стартовая страница сайта',
    date: '2019',
    client: 'Gym Station',
    clientLink: 'https://gym-s.ru',
    tags: 'логотип, фирменный стиль'
  },
  {
    title: 'Smart Park',
    type: ['presentation'],
    previewImage: 'Images/preview/smartpark.jpg',
    projectImage: ['Images/project/smartpark.jpg'],
    link: 'smartpark',
    description: 'Презентация технопарка в Зеленограде, Московской области',
    date: '2019',
    client: 'Dega Development',
    clientLink: 'https://dega-development.ru/',
    tags: 'презентация'
  },
  {
    title: 'Learn and Grow',
    type: ['style', 'polygraphy'],
    previewImage: 'Images/preview/grow.jpg',
    projectImage: ['Images/project/grow.jpg'],
    link: 'learnandgrow',
    description: 'Фирменный стиль мероприятия Learn and Grow для сотрудников компании Pepsico',
    date: '2020',
    client: 'ADA-Symposium',
    clientLink: 'https://ada-symposium.com/',
    tags: 'фирменный стиль'
  },
  {
    title: 'MeMeMeal',
    type: ['style', 'graphics'],
    previewImage: 'Images/preview/mememeal.jpg',
    projectImage: ['Images/project/meme1.jpg', 'Images/project/meme2.jpg'],
    link: 'mememeal',
    description: 'Фирменный стиль для службы доставки здорового питания',
    date: '2018',
    client: 'CETIS BRANDING AGENCY',
    clientLink: 'https://cetis.ru/',
    tags: 'логотип, упаковка, фирменный стиль'
  },
  {
    title: 'Банк проектов Москвы',
    type: ['web'],
    previewImage: 'Images/preview/bank.jpg',
    projectImage: ['Images/project/bank.jpg'],
    link: 'bank',
    description: 'Сайт единого банка проектов Москвы для поиска объектов для инвестиций',
    date: '2017',
    client: 'Ассоциация инвесторов Москвы',
    clientLink: 'http://aiminvest.ru/',
    tags: 'веб-дизайн'
  },
  {
    title: 'Константа',
    type: ['polygraphy', 'web'],
    previewImage: 'Images/preview/konstanta.jpg',
    projectImage: ['Images/project/constanta.jpg'],
    link: 'constanta',
    description: 'Публичный отчет о деятельности благотворительного фонда «Константа» за 2018 год В проекте используются фотографии Тверской области, где происходит деятельность фонда Набор отрыток и веб версия',
    date: '2019',
    client: 'Константа',
    clientLink: 'https://constanta-fund.ru/',
    tags: 'веб-дизайн, годовой отчет, открытка'
  },
  {
    title: 'iPark',
    type: ['presentation'],
    previewImage: 'Images/preview/ipark.jpg',
    projectImage: ['Images/project/odessa.jpg', 'Images/project/odessa1.jpg'],
    link: 'odessa',
    description: 'PPT-презентация для Индустриального парка в Одессе',
    date: '2019',
    client: 'DeGA Group',
    clientLink: 'https://dega-development.ru/',
    tags: 'презентация'
  },
  {
    title: 'Fluffy',
    type: ['style'],
    previewImage: 'Images/preview/fluffy.jpg',
    projectImage: ['Images/project/fluffy.jpg'],
    link: 'fluffy',
    description: 'Логотип, упаковка и эскиз оформления торговой точки по продаже эклеров. Идея горячих эклеров с холодным кремом взята из Японии, поэтому в оформлении используется стиль KAWAII* *Японское слово, означающее «милый», «прелестный», «хорошенький», «маленький».',
    date: '2019',
    client: 'BQB',
    clientLink: 'https://www.bqb.ru/',
    tags: 'логотип, упаковка'
  },
  {
    title: 'el Artecamino',
    type: ['style'],
    previewImage: 'Images/preview/artecamino.jpg',
    projectImage: ['Images/project/elartecamino.jpg', 'Images/project/elartecamino1.jpg'],
    link: 'elartecamino',
    description: 'Логотип и фирменный стиль для бутик-отеля в Аргентине «El Artecamino», название которого переводится как «искусство пути»',
    date: '2017',
    client: 'CETIS BRANDING AGENCY',
    clientLink: 'https://cetis.ru/',
    tags: 'логотип, фирменный стиль'
  },
  {
    title: 'ТИТР Медиа',
    type: ['web'],
    previewImage: 'Images/preview/titr.jpg',
    projectImage: ['Images/project/titr.jpg'],
    link: 'titr',
    description: 'Логотип и стартовая страница b2b сервиса для размещения рекламных кампаний в СМИ Пермского региона',
    date: '2018',
    client: 'ТИТР Медиа',
    clientLink: null,
    tags: 'логотип, ве-дизайн'
  },
  {
    title: 'Мойкомат',
    type: ['style'],
    previewImage: 'Images/preview/moykomat.png',
    projectImage: ['Images/project/moykomat.jpg', 'Images/project/moykomat1.jpg','Images/project/moykomat2.jpg'],
    link: 'moykomat',
    description: 'Логотип и общая концепция для сети моек самообслуживания. Мойкомат воплощен в жизнь и успешно развивается в Москве и Санкт-Петербурге.',
    date: '2018',
    client: 'CETIS BRANDING AGENCY',
    clientLink: 'https://moikomat.ru/',
    tags: 'логотип, фирменный стиль'
  },
  {
    title: 'Доброгород',
    type: ['polygraphy'],
    previewImage: 'Images/preview/dobrogorod.jpg',
    projectImage: ['Images/project/dobrogorod.jpg'],
    link: 'dobrogorod',
    description: 'Наружная реклама для жилого комплекса «Доброгород»',
    date: '2017',
    client: 'CETIS BRANDING AGENCY',
    clientLink: 'https://cetis.ru/',
    tags: 'наружная реклама'
  },
  {
    title: 'VNN',
    type: ['polygraphy'],
    previewImage: 'Images/preview/vnn.jpg',
    projectImage: ['Images/project/vnn.jpg', 'Images/project/vnn1.jpg'],
    link: 'vnn',
    description: 'Серия плакатов для немецких школ о пользе дополнительного образования',
    date: '2018',
    client: 'VNN',
    clientLink: 'https://www.nachhilfeschulen.org/',
    tags: 'плакат'
  },
  {
    title: 'В погоне за Йети',
    type: ['polygraphy', 'graphics'],
    previewImage: 'Images/preview/yeti.jpg',
    projectImage: ['Images/project/yeti.jpg', 'Images/project/yeti1.jpg'],
    link: 'yeti',
    description: 'Персонаж и афиша для лыжной гонки на кубок губернатора Кировской области',
    date: '2016 и 2018 гг',
    client: 'Правительство Кировской области',
    clientLink: 'https://www.kirovreg.ru/',
    tags: 'иллюстрация, плакат'
  },
  {
    title: '4SiS',
    type: ['style', 'polygraphy'],
    previewImage: 'Images/preview/4sis.png',
    projectImage: ['Images/project/4sis.jpg'],
    link: '4sis',
    description: 'Развитие фирменного стиля. Электронная и полиграфическая продукция для компании 4SIS: презентация, электронные письмо, билборд и визитка',
    date: '2016',
    client: '4SiS',
    clientLink: 'https://4sis.ru',
    tags: 'веб-дизайн, наружная реклама, презентация, фирменный стиль'
  },
  {
    title: 'Дирекция Центр',
    type: ['polygraphy'],
    previewImage: 'Images/preview/centr.jpg',
    projectImage: ['Images/project/centr.jpg'],
    link: 'centr',
    description: 'Две концепции буклета для одной из ведущих инжиниринговых компаний Москвы, осуществляющих управление проектами в строительстве.',
    date: '2014',
    client: 'ГД Центр',
    clientLink: 'https://gdcmoscow.ru/',
    tags: 'буклет'
  },
  {
    title: 'Moroshka',
    type: ['style'],
    previewImage: 'Images/preview/moroshka.jpg',
    projectImage: ['Images/project/moroshka.jpg'],
    link: 'moroshka',
    description: 'Логотип для российской марки натурального мороженого, выходящей на международный рынок',
    client: 'Moroshka',
    clientLink: null,
    date: '2016',
    tags: 'логотип'
  },
  {
    title: 'АльфаИС',
    type: ['web'],
    previewImage: 'Images/preview/alfais.jpg',
    projectImage: ['Images/project/alfais.jpg'],
    link: 'alfais',
    description: 'Лендинг двух обучающих вебинаров для компании АльфаИС',
    date: '2018',
    client: 'АльфаИС',
    clientLink: 'http://alfais.ru/',
    tags: 'веб-дизайн'
  },
  {
    title: 'На волне добра',
    type: ['polygraphy'],
    previewImage: 'Images/preview/dobro.jpg',
    projectImage: ['Images/project/volnadobra.jpg'],
    link: 'volnadobra',
    description: 'Годовой социальный отчет для благотворительного фонда «Constanta»',
    date: '2017',
    client: 'Константа',
    clientLink: 'https://constanta-fund.ru/',
    tags: 'буклет, годовой отчет'
  },
  {
    title: 'Eclair',
    type: ['style'],
    previewImage: 'Images/preview/eclair.jpg',
    projectImage: ['Images/project/eclair.jpg'],
    link: 'eclair',
    description: 'Магазин для кондитеров, где они могут купить необходимое для работы оборудование. Этот же логотип предполагалось использовать для учебного центра для кондитеров и небольшой кондитерской',
    client: 'Eclair',
    clientLink: null,
    date: '2016',
    tags: 'логотип, калиграфия'
  },
  {
    title: 'World Spa',
    type: ['style'],
    previewImage: 'Images/preview/spa.jpg',
    projectImage: ['Images/project/worldspa.jpg'],
    link: 'worldspa',
    description: 'Логотип для спа-салона класса «Премиум», г. Иркутск',
    date: '2016',
    client: 'World Spa',
    clientLink: 'https://www.worldspairk.ru/',
    tags: 'логотип'
  },
  {
    title: 'Invest Russia',
    type: ['presentation'],
    previewImage: 'Images/preview/invest.jpg',
    projectImage: ['Images/project/investrussia.jpg'],
    link: 'invest',
    description: 'Презентация для компании, занимающейся объединением российских и иностранных предприятий',
    client: 'INVEST IN RUSSIA',
    clientLink: 'https://investinrussia.com/',
    date: '2017',
    tags: 'презентация'
  },
  {
    title: 'Go, Romania!',
    type: ['polygraphy'],
    previewImage: 'Images/preview/romania.jpg',
    projectImage: ['Images/project/romania.jpg'],
    link: 'romania',
    description: 'Буклет для компании, занимающейся строительством коммерческой недвижимости',
    date: '2015',
    client: 'ACE',
    clientLink: 'https://acebranding.net/',
    tags: 'буклет'
  },
  {
    title: 'Рекламная компания',
    type: ['polygraphy'],
    previewImage: 'Images/preview/mercedes.jpg',
    projectImage: ['Images/project/mercedes.jpg'],
    link: 'mercedes',
    description: 'Зимняя рекламная кампания 2014 для сервисных центров Mercedes-Benz Идея: доступность в любом городе России',
    date: '2014',
    client: 'РА 4TE',
    clientLink: null,
    tags: 'наружная реклама'
  },
  {
    title: 'Anti Dote',
    type: ['style'],
    previewImage: 'Images/preview/antidote.jpg',
    projectImage: ['Images/project/antidote.jpg'],
    link: 'antidote',
    description: 'Разработка логотипа для нового бренда, выпускающего здоровые снеки и напитки',
    client: 'Anti Dote',
    clientLink: null,
    date: '2015',
    tags: 'логотип, каллиграфия'
  },
  {
    title: 'Quadroom',
    type: ['style'],
    previewImage: 'Images/preview/quadroom.jpg',
    projectImage: ['Images/project/quadroom.jpg'],
    link: 'quadroom',
    description: 'Логотип и фирменный стиль для бизнес-центра',
    client: 'Quadroom',
    clientLink: 'http://www.quadroom.ru/',
    date: '2013',
    tags: 'логотип, фирменный стиль'
  },
  {
    title: "Jane's story",
    type: ['style'],
    previewImage: 'Images/preview/jane.jpg',
    projectImage: ['Images/project/jane.jpg'],
    link: 'jane',
    description: 'Логотип для интернет-магазина женских сумок и аксессуаров',
    client: "Jane's story",
    clientLink: 'https://janesstory.ru/',
    date: '2013',
    tags: 'логотип, каллиграфия'
  },
  {
    title: "Outdoor workout",
    type: ['style'],
    previewImage: 'Images/preview/outdoor.jpg',
    projectImage: ['Images/project/outdoor.jpg'],
    link: 'outdoor',
    description: 'Нейминг и логотип для спортивного сообщества, посвященного тренировкам на свежем воздухе',
    client: 'Outdoor workout',
    clientLink: null,
    date: '2014',
    tags: 'логотип, нейминг'
  },
  {
    title: "Allegra",
    type: ['style', 'polygraphy'],
    previewImage: 'Images/preview/allegra.jpg',
    projectImage: ['Images/project/allegra.jpg'],
    link: 'allegra',
    description: '«ALLEGRA» – комплекс зданий с огороженной, автономной территорией в рамках проекта Индустриального парка «DEGA-Ногинск»',
    date: '2014',
    client: 'Аллегра',
    clientLink: 'https://dega-development.ru/',
    tags: 'буклет, логотип'
  },
  {
    title: "Ersta",
    type: ['style'],
    previewImage: 'Images/preview/ersta.jpg',
    projectImage: ['Images/project/ersta1.png', 'Images/project/ersta2.png', 'Images/project/ersta3.png', 'Images/project/ersta4.jpg', 'Images/project/ersta5.png'],
    link: 'ersta',
    description: 'Erste – первый (нем.) Компания Ersta в партнерстве с ведущими международными производителями профессиональной косметики предлагает комплексные решения по созданиюи развитию салонов красоты премум-класса. Для клиента сделаны: логотип, фирменный стиль, бренд-бук, шаблон электронной презентации',
    client: 'Ersta',
    clientLink: 'https://www.ersta.ru/',
    date: '2012',
    tags: 'логотип, презентация, фирменный стиль'
  },
  {
    title: "Totoroom",
    type: ['style', 'web'],
    previewImage: 'Images/preview/totoroom.png',
    projectImage: ['Images/project/totoroom.png', 'Images/project/totoroom1.jpg'],
    link: 'totoroom',
    description: 'Нейминг и логотип для интернет-магазина уникальных детских вещей totoroom.ru',
    client: 'Totoroom',
    clientLink: null,
    date: '2011',
    tags: 'фирменный стиль, веб-дизайн'
  },
  {
    title: "ТМК",
    type: ['presentation'],
    previewImage: 'Images/preview/tmk.png',
    projectImage: ['Images/project/tmk.png'],
    link: 'tmk',
    description: 'Электронный годовой отчет для Трубной Металлургической Компании',
    date: '2011',
    client: 'ТМК',
    clientLink: 'https://www.tmk-group.ru/',
    tags: 'фирменный стиль, веб-дизайн'
  },
  {
    title: "Александр Демышев",
    type: ['polygraphy', 'graphics'],
    previewImage: 'Images/preview/demyshev.jpg',
    projectImage: ['Images/project/papa.jpg'],
    link: 'demyshev',
    description: 'Каталог работ к юбилею художника',
    date: '2010',
    client: 'Александр Демышев',
    clientLink: 'http://demyshev.com/about',
    tags: 'буклет, журналы/книги'
  },
  {
    title: "Authentica",
    type: ['graphics'],
    previewImage: 'Images/preview/authenthica.jpg',
    projectImage: ['Images/project/authentica.jpg'],
    link: 'authentica',
    description: 'Подарочный набор открыток для косметической компании Authenthica с цитатами великих людей',
    client: 'Authentica',
    clientLink: 'https://www.authentica.ru/',
    date: '2012',
    tags: 'графика'
  },
  {
    title: "Серия детских книг",
    type: ['polygraphy', 'graphics'],
    previewImage: 'Images/preview/books.jpg',
    projectImage: ['Images/project/papa1.jpg', 'Images/project/papa2.jpg', 'Images/project/papa3.jpg', 'Images/project/papa4.jpg', 'Images/project/papa5.jpg', 'Images/project/papa6.jpg', 'Images/project/papa7.jpg', 'Images/project/papa8.jpg', 'Images/project/papa9.jpg', 'Images/project/papa10.jpg'],
    link: 'books',
    description: 'Совместный проект с художником Александром Дёмышевым Верстка и арт-дирекшн',
    date: '2012',
    client: 'Александр Демышев',
    clientLink: 'http://demyshev.com/about',
    tags: 'журналы/книги'
  },
];

export default Projects;